[phases.setup]
nixPkgs = [
  "chromium",
  "nss",
  "freetype",
  "harfbuzz",
  "ca-certificates",
  "glib",
  "dbus",
  "fontconfig",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXrandr",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXi",
  "xorg.libXrender",
  "xorg.libxtst",
  "alsa-lib",
  "at-spi2-atk",
  "gtk3",
  "pango",
  "cups"
]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build", "npm run prisma:generate"]

[start]
cmd = "npm run prisma:migrate && npm start"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
