[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run prisma:generate", "npm run build"]

[start]
cmd = "node dist/scripts/resolve-failed-migration.js && npx prisma migrate deploy && node dist/index.js"
